FROM python:3.9-slim

WORKDIR /app

# Instala as dependências (certifique-se que o streamlit está no pyproject.toml)
COPY pyproject.toml .
RUN pip install --no-cache-dir .

COPY . .

EXPOSE 8501

# Comando para rodar o Streamlit
CMD ["streamlit", "run", "01_🎬LinRecom.py", "--server.port=8501", "--server.address=0.0.0.0"]